/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sudhir Kushwaha
 */
public class AddBook extends javax.swing.JFrame {

    /**
     * Creates new form AddBook
     */
    public AddBook() {
        initComponents();
    }
    public void clear(){
        txtcode.setText("");
        txtname.setText("");
        txtauthor.setText("");
        txtpublisher.setText("");
        txtpurchase.setText("");
         txtedtion.setText("");
         txtyear.setText("");
         txtpages.setText("");
         txtvolume.setText("");
         txtsource.setText("");
           txtprice.setText("");
         txtisbn.setText("");
        // combotype.setText("");
         
          
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtauthor = new javax.swing.JTextField();
        txtcode = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtpublisher = new javax.swing.JTextField();
        txtpurchase = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        combotype = new javax.swing.JComboBox<>();
        txtedtion = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        txtpages = new javax.swing.JTextField();
        txtvolume = new javax.swing.JTextField();
        txtsource = new javax.swing.JTextField();
        txtisbn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close icon.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1088, 0, 50, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Acc No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 239, 46));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Book Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 239, 46));

        btnsave.setBackground(new java.awt.Color(204, 0, 0));
        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(242, 242, 242));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Author");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 239, 46));

        txtauthor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtauthor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtauthorKeyPressed(evt);
            }
        });
        getContentPane().add(txtauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 320, 40));

        txtcode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodeKeyPressed(evt);
            }
        });
        getContentPane().add(txtcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 320, 40));

        txtname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 320, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/isue.jpg"))); // NOI18N
        jLabel1.setText("Add Book Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 230, 53));

        txtpublisher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpublisher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpublisherKeyPressed(evt);
            }
        });
        getContentPane().add(txtpublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 320, 40));

        txtpurchase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpurchase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpurchaseKeyPressed(evt);
            }
        });
        getContentPane().add(txtpurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 320, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Publisher");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 239, 46));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Edition");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 239, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 239, 46));

        txtprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpriceKeyPressed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 320, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Volume");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 239, 46));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Year");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 239, 46));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Purchase");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 239, 46));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Source");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 239, 46));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Book Type");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 239, 46));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Pages");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 239, 46));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("ISBN No.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 239, 46));

        combotype.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combotype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Book Type", "PB", "HB" }));
        combotype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combotypeKeyPressed(evt);
            }
        });
        getContentPane().add(combotype, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, 250, 40));

        txtedtion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtedtion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtedtionKeyPressed(evt);
            }
        });
        getContentPane().add(txtedtion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 320, 40));

        txtyear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtyearKeyPressed(evt);
            }
        });
        getContentPane().add(txtyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 320, 40));

        txtpages.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpagesKeyPressed(evt);
            }
        });
        getContentPane().add(txtpages, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 320, 40));

        txtvolume.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtvolume.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvolumeKeyPressed(evt);
            }
        });
        getContentPane().add(txtvolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 320, 40));

        txtsource.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtsource.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsourceKeyPressed(evt);
            }
        });
        getContentPane().add(txtsource, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 320, 40));

        txtisbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtisbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtisbnKeyPressed(evt);
            }
        });
        getContentPane().add(txtisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 320, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/All Page Backgraound.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        PreparedStatement pst;
        Connection c=Connect.ConnectToDB();
        if(txtcode.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Please enter Book code");
                txtcode.requestFocus();
        }
        else if(txtname.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Please enter Book Name");
                txtname.requestFocus();
        }
        else if(txtauthor.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Please enter Author");
                txtauthor.requestFocus();
        }
        else if(txtpublisher.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Please enter publisher");
                txtpublisher.requestFocus();
        }
        else if(txtpurchase.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Please enter purchase");
                txtpurchase.requestFocus();
        }
        else if(txtprice.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Please enter price");
                txtprice.requestFocus();
        }
        else{
        try {
            pst=c.prepareStatement("INSERT INTO library.book (bcode , bname ,author,publisher ,purchase,price,edition,year,pages,volume,source,isbn,type,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, txtcode.getText());
            pst.setString(2, txtname.getText());
            pst.setString(3, txtauthor.getText());
            pst.setString(4, txtpublisher.getText());
            pst.setString(5, txtpurchase.getText());
            pst.setString(6, txtprice.getText());
            pst.setString(7, txtedtion.getText());
            pst.setString(8, txtyear.getText());
            pst.setString(9, txtpages.getText());
            pst.setString(10, txtvolume.getText());
            pst.setString(11, txtsource.getText());
            pst.setString(12, txtisbn.getText());
            pst.setString(13, combotype.getItemAt(combotype.getSelectedIndex()));
            pst.setString(14, "Available");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Record Saved","Saved",JOptionPane.INFORMATION_MESSAGE);
            clear();
        } catch (SQLException ex) {
            Logger.getLogger(AddBook.class.getName()).log(Level.SEVERE, null, ex);
        } 
            }// TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodeKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
                txtname.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodeKeyPressed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
                txtauthor.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtauthorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtauthorKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
                txtpublisher.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtauthorKeyPressed

    private void txtpublisherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpublisherKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
                txtedtion.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtpublisherKeyPressed

    private void txtpurchaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpurchaseKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
               txtpages.requestFocus();   

        // TODO add your handling code here:
    }//GEN-LAST:event_txtpurchaseKeyPressed

    private void txtpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
      txtisbn.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceKeyPressed

    private void txtedtionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedtionKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     txtyear.requestFocus();   // TODO add your handling code here:
    }//GEN-LAST:event_txtedtionKeyPressed

    private void txtyearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtyearKeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     txtpurchase.requestFocus(); 

        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearKeyPressed

    private void txtpagesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagesKeyPressed

if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     txtvolume.requestFocus(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagesKeyPressed

    private void txtvolumeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvolumeKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     txtsource.requestFocus(); 
 // TODO add your handling code here:
    }//GEN-LAST:event_txtvolumeKeyPressed

    private void txtsourceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsourceKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     txtprice.requestFocus();  // TODO add your handling code here:
    }//GEN-LAST:event_txtsourceKeyPressed

    private void txtisbnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtisbnKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     combotype.requestFocus();  // TODO add your handling code here:
    }//GEN-LAST:event_txtisbnKeyPressed

    private void combotypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combotypeKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     btnsave.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_combotypeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> combotype;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtedtion;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpages;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtpublisher;
    private javax.swing.JTextField txtpurchase;
    private javax.swing.JTextField txtsource;
    private javax.swing.JTextField txtvolume;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
