
import com.mysql.cj.xdevapi.Statement;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ANIKA WALIA
 */
public class Billprint extends javax.swing.JFrame {
    
    String id=transactions.id;
    String bcode=transactions.bcode;
    String bname=transactions.bname;
    String strollno=transactions.strollno;
    String stname=transactions.stname;
    String contactno=transactions.contactno;
    String course=transactions.course;
    String issuedate=transactions.issuedate;
    String duedate=transactions.duedate;
    String returndate=transactions.returndate;
    String fine=transactions.fine;
     PreparedStatement pst;
        Statement st;
        ResultSet rs;

    /**
     * Creates new form Billprint
     */
    public Billprint() {
        initComponents();
       // Connect();
      // PreparedStatement pst;
       // Statement st;
       // ResultSet rs;
        Connection c=Connect.ConnectToDB();
     try {
            pst=c.prepareStatement("SELECT * FROM library.st_transactions where st_id=?");
            pst.setString(1, id);
            rs=pst.executeQuery();
            if(rs.next()){
                stname=rs.getString("stname");
                strollno=rs.getString("strollno");
                contactno=rs.getString("contactno");
                course=rs.getString("course");
                 bcode=rs.getString("bcode");
                bname=rs.getString("bname");
               issuedate=rs.getString("issuedate");
               duedate=rs.getString("duedate");
                  returndate=rs.getString("returndate"); 
                  fine=rs.getString("fine");
            }
     } catch (SQLException ex) {
            Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        } 
        txtbill.setText("\t\t Library Management System \n");
        txtbill.setText( txtbill.getText()+"                     **************************************************************\n");
       // txtbill.setText( txtbill.getText()+"***************************************************************\n");
        txtbill.setText( txtbill.getText()+"Sr No.:-"+id+"\n\n");
        txtbill.setText( txtbill.getText()+"                     Student Details:-\n");
        txtbill.setText( txtbill.getText()+"                   ************************\n");
        txtbill.setText( txtbill.getText()+"Student Name:-"+stname+"\n");
        txtbill.setText( txtbill.getText()+"Roll_no:-"+strollno+"\n");
        txtbill.setText( txtbill.getText()+"Contact_no:-"+contactno+"\n");
        txtbill.setText( txtbill.getText()+"Course:-"+course+"\n");
        txtbill.setText( txtbill.getText()+"                    ***************************************************************\n\n");
        txtbill.setText( txtbill.getText()+"                      Book Details:-\n");
        txtbill.setText( txtbill.getText()+"                   ************************\n");
        txtbill.setText( txtbill.getText()+"Acc No:-"+bcode+"\n");
        txtbill.setText( txtbill.getText()+"Book Name:-"+bname+"\n");
        txtbill.setText( txtbill.getText()+"Issue Date:-"+issuedate+"\n");
        txtbill.setText( txtbill.getText()+"Due Date:-"+duedate+"\n");
        txtbill.setText( txtbill.getText()+"Return Date:-"+returndate+"\n");
        txtbill.setText( txtbill.getText()+"Fine:-"+fine+"\n");
    }
    
    
    
    
   /* public void connect(){
        PreparedStatement pst;
        Statement st;
        ResultSet rs;
        Connection c=Connect.ConnectToDB();
     try {
            pst=c.prepareStatement("SELECT * FROM library.st_transactions where bcode=?");
            pst.setString(1, id);
            rs=pst.executeQuery();
            if(rs.next()){
                strollno=rs.getString("strollno");
                stname=rs.getString("stname");
                bname=rs.getString("bname");
                bcode=rs.getString("bcode");
                issuedate=rs.getString("issuedate");
                   
            }
     } catch (SQLException ex) {
            Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnclose = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbill.setEditable(false);
        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtbill.setRows(5);
        jScrollPane1.setViewportView(txtbill);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 770, 530));

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close icon.png"))); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 50, 40));

        btnprint.setBackground(new java.awt.Color(0, 0, 255));
        btnprint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnprint.setForeground(new java.awt.Color(255, 255, 255));
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel1.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
         dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
     
        try{
            txtbill.print();
            }catch (PrinterException ex) {
            Logger.getLogger(Billprint.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnprintActionPerformed
    
   
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billprint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnprint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtbill;
    // End of variables declaration//GEN-END:variables
}
