/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.UIManager.getString;
import java.util.Scanner;
import java.time.*;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author Sudhir Kushwaha
 */
public class ReturnBook extends javax.swing.JFrame {
    Connection c=Connect.ConnectToDB();
    PreparedStatement pst;
    ResultSet rs;
    
                
    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
       SimpleDateFormat  dat=new SimpleDateFormat("dd/MM/yyyy ");
        Date d=new Date();
        // txtreturndate.setText(dat.format(d));
        txtperday.setText("2");
    }
    public void clear(){
        txtbookid.setText("");
        txtbookname.setText("");
        txtreturndate.setText("");
        txtstrollno.setText("");
        txtstname.setText("");
         txtstno.setText("");
          txtissuedate.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        txtreturndate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnreturn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtbookname = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        txtstrollno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtstname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtissuedate = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtstno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LBLDMY = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtperday = new javax.swing.JTextField();
        txtfinedays = new javax.swing.JTextField();
        txtfine = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close icon.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1088, 0, 50, -1));

        txtreturndate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtreturndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 350, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Acc_No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 270, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Sr_No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 270, 50));

        btnreturn.setBackground(new java.awt.Color(204, 0, 0));
        btnreturn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnreturn.setForeground(new java.awt.Color(242, 242, 242));
        btnreturn.setText("Return");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 130, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Issue Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 270, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Return Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 270, 50));

        txtbookname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 350, 40));

        txtbookid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 350, 40));

        txtstrollno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtstrollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 350, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/isue.jpg"))); // NOI18N
        jLabel1.setText("Return Book");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, 60));

        txtstname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 350, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Student Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 220, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Book Title");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 220, 50));

        txtissuedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 350, 40));

        btnsearch.setBackground(new java.awt.Color(204, 0, 0));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(242, 242, 242));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 90, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Fine Days");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 270, 50));

        txtstno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtstno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 350, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Student Rollno.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 270, 50));

        LBLDMY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(LBLDMY, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 270, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Per Day Fine");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 270, 50));

        txtperday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtperday, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 250, 40));
        getContentPane().add(txtfinedays, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 250, 40));
        getContentPane().add(txtfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 250, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Total Fine");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 270, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/All Page Backgraound.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
  /*  public  double calculateFine()
    { try{
        String s1,s2;
        s1=txtreturndate.getText();
                s2= txtissuedate.getText();
                Date d1=format.parse(s1);
                Date d2=format.parse(s2);
                SimpleDateFormat  format=new SimpleDateFormat("dd/MM/yyyy ");
                Date d1=format.parse(s1);
                 long daysBetween = ChronoUnit.DAYS.between(d1, d2);
         } catch (Exception e) {
            e.printStackTrace();
            return 0;
        }
    
        return 0; 
    }
    */
    private void fine_calculate()
    {
            try
            {
                
                String s1,s2;
                int fine=2;
                s1=txtreturndate.getText();
                s2= txtissuedate.getText();
                int issuedays=14;
                SimpleDateFormat  format=new SimpleDateFormat("dd/MM/yyyy ");
                Date d1=format.parse(s1);
                Date d2=format.parse(s2);
                long diff=d1.getTime()-d2.getTime();
                int totaldays=(int)diff/(24*60*1000);
                int finedays=totaldays-issuedays;
               
               // System.out.print(diff);
              // double totalfine=finedays*fine;
               if(finedays==0)
                   finedays=1;
               txtfinedays.setText(String.valueOf(finedays));
               double totalfine=Double.valueOf(getString(txtperday))*finedays;
               txtfine.setText(String.valueOf(totalfine));
                LBLDMY.setText("diff");
              if(finedays>issuedays)
              {
                  LBLDMY.setText("in func");
                     pst=c.prepareStatement("UPDATE library.st_transactions SET fine=? WHERE bcode = ?");
                     pst.setString(1,String.valueOf(totalfine));
                     pst.setString(2, txtbookid.getText());
                     pst.executeUpdate();
                 }
               else
                        {
                            pst=c.prepareStatement("UPDATE library.st_transactions SET fine=? WHERE returndate = ?");
                            pst.setString(1,"NULL");
                            pst.setString(2, txtreturndate.getText());
                            pst.executeUpdate();
                        }   
            
            }
            catch (SQLException ex) {
                Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch (ParseException ex) {
                Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
            }

    }
    
    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        if(txtstno.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Please enter Accession Number and Search it again");
                txtstno.requestFocus();
        }
        else{
            try{
               pst=c.prepareStatement("SELECT * from library.st_transactions where st_id=?  and status=? " );
               pst.setString(1, txtstno.getText());
                  pst.setString(2,"Available");
             //    pst.setString(3, txtstrollno.getText());
          rs=pst.executeQuery();
            if(rs.next()){
               JOptionPane.showMessageDialog(this, "Alraedy Returned");}
          else{
                 fine_calculate();
            pst=c.prepareStatement("UPDATE library.st_transactions SET status =?,returndate=? WHERE st_id = ?");
            //pst=c.prepareStatement(" UPDATE library.st_transactions SET bcode=? , bname=? ,strollno=?,stname=?,contactno=?,course=? ,issuedate=?,duedate=?,returndate=?,status=? WHERE (bcode=?)");
            pst.setString(1,"AVAILABLE");  
            pst.setString(3, txtstno.getText());
            pst.setString(2, txtreturndate.getText());
           /* pst.setString(2, " ");
            pst.setString(3, " ");
            pst.setString(4, " ");
            pst.setString(5, " ");
            pst.setString(6, " ");
            pst.setString(7, " ");
            pst.setString(8, " ");
            pst.setString(9, txtreturndate.getText());
             pst.setString(10,"AVAILABLE"); 
           pst.setString(11, " ");*/
            pst.executeUpdate();
            pst=c.prepareStatement("UPDATE library.book SET status =? WHERE bcode = ?");
            pst.setString(1,"Available");
            pst.setString(2, txtbookid.getText());
             pst.executeUpdate();
              //fine_calculate();
            JOptionPane.showMessageDialog(this, "Return Successfull");
            clear();
           
            
            }
            }catch (SQLException ex) {
                Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            
         //  fine_calculate();
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnreturnActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed

            try {
            pst=c.prepareStatement("SELECT * FROM library.st_transactions where st_id=?");
            pst.setString(1, txtstno.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                txtstrollno.setText(rs.getString("strollno"));
                     txtstname.setText(rs.getString("stname"));
                    txtbookname.setText(rs.getString("bname"));
                    txtbookid.setText(rs.getString("bcode"));
                    txtissuedate.setText(rs.getString("issuedate"));
                   
            }
            else
                JOptionPane.showMessageDialog(this, "Please Enter Valied Accession Number");
            /*pst=c.prepareStatement("SELECT * FROM library.student where id=?");
            pst.setString(1, txtstudentid.getText());
            rs=pst.executeQuery();
            if(rs.next())
                    txtstudentname.setText(rs.getString("name"));
           */ 
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLDMY;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtfinedays;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtperday;
    private javax.swing.JTextField txtreturndate;
    private javax.swing.JTextField txtstname;
    private javax.swing.JTextField txtstno;
    private javax.swing.JTextField txtstrollno;
    // End of variables declaration//GEN-END:variables
}
